### ISSUE TITLE
"mask_valid" parameter

### ISSUE THREAD

**Issue by kalyani7195** [EPFL-VILAB/MultiMAE#27]
Hi! Thanks for the great work! 💯 
I am a bit confused about this parameter the in yaml file -- 
`use_mask_valid: True # Requires "task" mask_valid to be saved to disk`

When I set that to False --I get the following error  while 
 fine-tuning a ViT based model on the NYU dataset-- 

```
Original Traceback (most recent call last):
  File "/gscratch/sciencehub/kmarathe/miniconda3/envs/py38/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/gscratch/sciencehub/kmarathe/miniconda3/envs/py38/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/gscratch/sciencehub/kmarathe/miniconda3/envs/py38/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mmfs1/gscratch/sciencehub/kmarathe/models/SSL/MAE/mae/evals/MultiMAE/utils/dataset_folder.py", line 307, in __getitem__
    sample_dict = self.transform(sample_dict)
  File "/mmfs1/gscratch/sciencehub/kmarathe/models/SSL/MAE/mae/evals/MultiMAE/utils/dataset_regression.py", line 120, in __call__
    task_dict['mask_valid'] = (task_dict['mask_valid'] == 255)[None]
```
KeyError: 'mask_valid'

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/13524848/230748049-0a685d80-1342-44f7-a5a9-e4a693201143.png">

When I set that to True -- I get the following. I used the provided script to create the NYU dataset. -- It did save train test data and depth maps, but there was no folder called mask_valid.

```

RuntimeError: Found 0 logs in subfolders of: /gscratch/sciencehub/vision_datasets/NYU/train/mask_valid
Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif,.tiff,.webp,.jpx

```
 

I am definitely missing something and any help here is greatly appreciated. 

Thanks and regards,
Kalyani

**Comment by tyleryzhu** [comment]
Does #25 help with your query? I found a similar problem and tracked it down to that.

**Comment by ko973** [comment]
Pls I beg you can you help

**Comment by ko973** [comment]
> Does #25 help with your query? I found a similar problem and tracked it down to that. 

Pls pls I need more to uncoding pls help me I doing it 3rh day .Can I send you all to uncoding

**Comment by ko973** [comment]
> Hi! Thanks for the great work! 💯 
> I am a bit confused about this parameter the in yaml file -- 
> `use_mask_valid: True # Requires "task" mask_valid to be saved to disk`
> 
> When I set that to False --I get the following error  while 
>  fine-tuning a ViT based model on the NYU dataset-- 
> 
> ```
> Original Traceback (most recent call last):
>   File "/gscratch/sciencehub/kmarathe/miniconda3/envs/py38/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/gscratch/sciencehub/kmarathe/miniconda3/envs/py38/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/gscratch/sciencehub/kmarathe/miniconda3/envs/py38/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/mmfs1/gscratch/sciencehub/kmarathe/models/SSL/MAE/mae/evals/MultiMAE/utils/dataset_folder.py", line 307, in __getitem__
>     sample_dict = self.transform(sample_dict)
>   File "/mmfs1/gscratch/sciencehub/kmarathe/models/SSL/MAE/mae/evals/MultiMAE/utils/dataset_regression.py", line 120, in __call__
>     task_dict['mask_valid'] = (task_dict['mask_valid'] == 255)[None]
> ```
> KeyError: 'mask_valid'
> 
> <img width="1044" alt="image" src="https://user-images.githubusercontent.com/13524848/230748049-0a685d80-1342-44f7-a5a9-e4a693201143.png">
> 
> 
> 
> When I set that to True -- I get the following. I used the provided script to create the NYU dataset. -- It did save train test data and depth maps, but there was no folder called mask_valid.
> 
> ```
> 
> RuntimeError: Found 0 logs in subfolders of: /gscratch/sciencehub/vision_datasets/NYU/train/mask_valid
> Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif,.tiff,.webp,.jpx
> 
> ```
>  
> 
> I am definitely missing something and any help here is greatly appreciated. 
> 
> Thanks and regards,
> Kalyani
> 
> 

> I have more ia what I found under my ID NUMBER .I need so much help with it pls pls can I send you all data I found

**Comment by ShreyGanatra** [comment]
Facing similar problem as @kalyani7195.
![image](https://github.com/EPFL-VILAB/MultiMAE/assets/77409139/d56678c1-b49a-4e0b-b37d-de590c1af5ff)
I am getting this as dataset after running  `prepare_nyuv2.py`

Any help here is greatly appreciated.
